services:
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: 'todoapp'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - ./db_data:/var/lib/mysql

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - li
    volumes:
      - .docker.env:/app/.env
    environment:
      - TZ=Europe/Lisbon

  li:
    image: brito/liquibase:latest
    depends_on:
      - db
    build:
      dockerfile: liqui.Dockerfile
      context: .
    volumes:
      - ./db:/app
#    command: "--defaults-file=/app/liquibase.properties validate"
    command: "--defaults-file=/app/liquibase.properties update"
#    command: "--defaults-file=/app/liquibase.properties changelog-sync"