services:
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: 'todoapp'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - ./db_data:/var/lib/mysql

  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .docker.env:/app/.env

