services:
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: 'todoapp'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: