### Create New Task
POST http://localhost:8080/tasks
Content-Type: application/json

{
    "description": "{{$isoTimestamp}}"
}


### Update Task
PUT http://localhost:8080/tasks/0
Content-Type: application/json

{
    "description": "smt new 1 updatyed",
    "done": false
}

### Get Task By ID
GET http://localhost:8080/tasks/8c7d1730-5985-11ef-8057-0242ac140001


### Delete Task
DELETE http://localhost:8080/tasks/0


### Create User
POST http://localhost:8080/users
Content-Type: application/json

{
    "username": "username1",
    "password": "password1",
    "email": "main@vitorbrito.com"
}