### Create New Task
POST http://localhost:8080/tasks
Content-Type: application/json

{
    "description": "{{$isoTimestamp}}",
    "userId": "18e43df6-6523-11ef-82f4-4eda08cebcc7"
}

### Get All Tasks
GET http://localhost:8080/tasks
Content-Type: application/json
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkNoZWsiLCJleHAiOjE3MjU1NDYwMTN9.h3jzMEXA-gZzNpGQ271eVSqx_iOQG8_2A2zJuxH9tiI

### Update Task
PUT http://localhost:8080/tasks/af558216-6525-11ef-bf90-4eda08cebcc7
Content-Type: application/json

{
    "description": "smt new 1 updatyed",
    "done": false
}

### Get Task By ID
GET http://localhost:8080/tasks/8c7d1730-5985-11ef-8057-0242ac140001


### Delete Task
DELETE http://localhost:8080/tasks/fb12e2aa-5f00-11ef-bd14-4eda08cebcc7

### Create User
POST http://localhost:8080/users
Content-Type: application/json

{
    "username": "username1",
    "password": "password1",
    "email": "main@vitorbrito.com"
}

### Log In
POST http://localhost:8080/auth
Content-Type: application/json

{
    "username": "Chek",
    "password": "123456"
}

### Protected
POST http://localhost:8080/protected
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkNoZWsiLCJleHAiOjE3MjU1NDYwMTN9.h3jzMEXA-gZzNpGQ271eVSqx_iOQG8_2A2zJuxH9tiI

{
    "username": "Chek",
    "password": "123456"
}